#Developpement docker-compose file by Uniride
version: '3.8'

services:

#This container is used to get the frontend
  uniride_frontend:
    container_name: uniride_frontend
    image: uniride1/uniride_front #automatically latest
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - uniride_backend
    volumes:
      - ./certs/:/app/certs

#This container is used to get the backend
  uniride_backend:
    container_name: uniride_backend
    image: uniride1/uniride_back #automatically latest
    restart: always
    #This volume is used to store the uploaded files and the certificates
    volumes:
      - ./documents/id_card/:/usr/src/app/documents/id_card
      - ./documents/insurance/:/usr/src/app/documents/insurance
      - ./documents/license/:/usr/src/app/documents/license
      - ./documents/pft/:/usr/src/app/documents/pft
      - ./documents/school_certificate/:/usr/src/app/documents/school_certificate
      - ./certs/:/usr/src/app/uniride_sme/certs
    depends_on:
      - uniride_redis
      - uniride_db
    ports:
      - "5050:5050"
    env_file: #This file contains the environment variables, cause the image is not built with them
      - ./env/uniride-backend-template.env

#This container is used to add cache to the backend
  uniride_redis:
    container_name: uniride_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

#This container is used to store the data
  uniride_db:
    container_name: uniride_db
    image: uniride1/uniride_bdd #automatically latest
    restart: always
    env_file:
      - ./env/uniride-db-template.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data #data storage, to keep the data after the container is stopped (need to create the folder before if not exist)

x-environment:
  COMPOSE_PROJECT_NAME: uniride